# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        config_admin:
            # uiColor: "#f3f4f5"
            # toolbar: [ ["NewPage","-","Templates","-","Undo","Redo"], ["Bold","Italic","Underline","Strike","Subscript","Superscript","-","RemoveFormat"], ["Image","Table","HorizontalRule","SpecialChar","PageBreak","Iframe"], ["Link","Unlink","Anchor"], ["Find","Replace","-","-","Scayt"], "\/", ["NumberedList","BulletedList","-","Outdent","Indent","-","-","JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock"], ["Styles","Format","FontSize","TextColor","BGColor"], ["Maximize","ShowBlocks", "Source"] ]
            # allowedContent: true
            # filebrowserBrowseRoute: 'elfinder'
            # filebrowserBrowseRouteParameters:
            #     instance: 'instance_admin' # config instance name below
            # extraPlugins: 'templates'
            # templates:    'templates_perso'
            # templates_replaceContent: false   #Permet de désactiver le remplacer contenu par défaut
            # stylesSet:    'styles_perso'
            # contentsCss: 'bundles/sfbadmin/styles/ckeditor.css' #css d'affichage wysi
